twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['forms/bootstrap_4_layout.html.twig']
    globals:
        base_url: '%env(BASE_URL)%'
        googleApiKey: '%env(GOOGLE_API_KEY)%'
        app_version: '%env(APP_VERSION)%'
        thumbnail_url: '%env(BASE_URL)%/%env(THUMBNAIL_FILE)%'
        app_name: '%env(APP_NAME)%'
when@test:
    twig:
        strict_variables: true
