<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LocationCountry extends \App\Entity\LocationCountry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'name', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'alpha3', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'native', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'alpha2', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'callingCode', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'states', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'users'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'id', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'name', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'alpha3', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'native', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'alpha2', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'callingCode', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'states', '' . "\0" . 'App\\Entity\\LocationCountry' . "\0" . 'users'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LocationCountry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlpha3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlpha3', []);

        return parent::getAlpha3();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlpha3(?string $alpha3): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlpha3', [$alpha3]);

        return parent::setAlpha3($alpha3);
    }

    /**
     * {@inheritDoc}
     */
    public function getNative(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNative', []);

        return parent::getNative();
    }

    /**
     * {@inheritDoc}
     */
    public function setNative(string $native): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNative', [$native]);

        return parent::setNative($native);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlpha2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlpha2', []);

        return parent::getAlpha2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlpha2(string $alpha2): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlpha2', [$alpha2]);

        return parent::setAlpha2($alpha2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCallingCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCallingCode', []);

        return parent::getCallingCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCallingCode(?string $callingCode): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCallingCode', [$callingCode]);

        return parent::setCallingCode($callingCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStates(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStates', []);

        return parent::getStates();
    }

    /**
     * {@inheritDoc}
     */
    public function addState(\App\Entity\LocationState $state): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addState', [$state]);

        return parent::addState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function removeState(\App\Entity\LocationState $state): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeState', [$state]);

        return parent::removeState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\User $user): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\User $user): \App\Entity\LocationCountry
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

}
