<?php

namespace ContainerNBaxtRd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JCffzLkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JCffzLk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JCffzLk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'user' => ['privates', '.errored..service_locator.JCffzLk.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.JCffzLk": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'translator' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
