<?php

namespace ContainerNBaxtRd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsAddressTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SettingsAddressType' shared autowired service.
     *
     * @return \App\Form\SettingsAddressType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SettingsAddressType.php';

        return $container->privates['App\\Form\\SettingsAddressType'] = new \App\Form\SettingsAddressType(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['App\\Form\\Helper\\LocationHelper'] ?? $container->load('getLocationHelperService')), ($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()));
    }
}
