<?php

namespace ContainerNBaxtRd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UserAdminCommand' shared autowired service.
     *
     * @return \App\Command\UserAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UserAdminCommand.php';

        $container->privates['App\\Command\\UserAdminCommand'] = $instance = new \App\Command\UserAdminCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:user-admin:create');
        $instance->setDescription('Command to create an admin user.');

        return $instance;
    }
}
