<?php

namespace ContainerNBaxtRd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebsiteExtensionRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Runtime\WebsiteExtensionRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\WebsiteExtensionRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Runtime/WebsiteExtensionRuntime.php';

        return $container->privates['App\\Twig\\Runtime\\WebsiteExtensionRuntime'] = new \App\Twig\Runtime\WebsiteExtensionRuntime($container->getEnv('BASE_URL').'/'.$container->getEnv('string:THUMBNAIL_FILE'), 'en|de|pt', ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['App\\Utils\\Acl'] ?? $container->load('getAclService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
