<?php

namespace Container401P3OD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAclService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Utils\Acl' shared autowired service.
     *
     * @return \App\Utils\Acl
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utils/Acl.php';

        return $container->privates['App\\Utils\\Acl'] = new \App\Utils\Acl(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
