<?php

namespace Container401P3OD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAclExtensionRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Runtime\AclExtensionRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\AclExtensionRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Runtime/AclExtensionRuntime.php';

        return $container->privates['App\\Twig\\Runtime\\AclExtensionRuntime'] = new \App\Twig\Runtime\AclExtensionRuntime(($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()));
    }
}
