<?php

namespace Container401P3OD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Helper\LocationHelper' shared autowired service.
     *
     * @return \App\Form\Helper\LocationHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Form/Helper/LocationHelper.php';

        return $container->privates['App\\Form\\Helper\\LocationHelper'] = new \App\Form\Helper\LocationHelper(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
