<?php

namespace Container401P3OD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAddTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserAddType' shared autowired service.
     *
     * @return \App\Form\UserAddType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserAddType.php';

        return $container->privates['App\\Form\\UserAddType'] = new \App\Form\UserAddType(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['App\\Form\\Helper\\LocationHelper'] ?? $container->load('getLocationHelperService')), ($container->privates['App\\Service\\UploaderHelper'] ?? $container->load('getUploaderHelperService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ['limitHeightAvatarUser' => $container->getEnv('UPLOAD_LIMIT_HEIGHT_USER_AVATAR'), 'directoryTmp' => $container->getEnv('UPLOAD_DIRECTORY_TMP')]);
    }
}
