<?php

namespace Container401P3OD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdminCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\UserAdminCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\UserAdminCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:user-admin:create', [], 'Command to create an admin user.', false, #[\Closure(name: 'App\\Command\\UserAdminCommand')] function () use ($container): \App\Command\UserAdminCommand {
            return ($container->privates['App\\Command\\UserAdminCommand'] ?? $container->load('getUserAdminCommandService'));
        });
    }
}
