<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNBaxtRd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNBaxtRd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNBaxtRd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNBaxtRd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNBaxtRd\App_KernelDevDebugContainer([
    'container.build_hash' => 'NBaxtRd',
    'container.build_id' => '2069fe47',
    'container.build_time' => 1673790539,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNBaxtRd');
