<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_settings_security' => [['_locale'], ['_controller' => 'App\\Controller\\Admin\\SettingsController::security', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/admin/settings/security'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'admin_settings_profile' => [['_locale'], ['_controller' => 'App\\Controller\\Admin\\SettingsController::profile', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/admin/settings/profile'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'admin_settings_address' => [['_locale'], ['_controller' => 'App\\Controller\\Admin\\SettingsController::address', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/admin/settings/address'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'admin_user_index' => [['_locale'], ['_controller' => 'App\\Controller\\Admin\\UserController::index', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/users'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'admin_user_edit' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\Admin\\UserController::edit', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'admin_user_add' => [['_locale'], ['_controller' => 'App\\Controller\\Admin\\UserController::add', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/user/add'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'security_login' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::login', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/login'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'security_logout' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::logout', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/logout'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'api_location_city_list' => [['_locale'], ['_controller' => 'App\\Controller\\Api\\LocationCityController::listAction', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/api/location/cities'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'api_location_country_get' => [['_locale'], ['_controller' => 'App\\Controller\\Api\\LocationCountryController::getAction', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/api/location/country'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'api_location_country_search' => [['_locale'], ['_controller' => 'App\\Controller\\Api\\LocationCountryController::searchAction', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/api/location/country/search'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    'api_location_state_list' => [['_locale'], ['_controller' => 'App\\Controller\\Api\\LocationStateController::listAction', '_locale' => 'en'], ['_locale' => 'en|de|pt'], [['text', '/api/location/states'], ['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'liip_imagine_filter_runtime' => [['filter', 'hash', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterRuntimeAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[^/]++', 'hash', true], ['text', '/rc'], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], [], []],
    'liip_imagine_filter' => [['filter', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'login' => [['_locale'], ['template' => 'security/login.html.twig', '_locale' => 'en', '_controller' => 'App\\Controller\\SecurityController::login'], ['_locale' => 'en|de|pt'], [['variable', '/', 'en|de|pt', '_locale', true]], [], [], []],
];
