<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'main' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_sulu_web_packages_core_core_js-node_modules_admin-lte_dist_js_adminlte_m-501f93.js',
                '/build/main.js',
            ],
            'css' => [
                '/build/vendors-node_modules_sulu_web_packages_core_core_js-node_modules_admin-lte_dist_js_adminlte_m-501f93.css',
                '/build/main.css',
            ],
        ],
    ],
],

]];
